import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'
import App from './App'
import { Box, Container, Flex, Grid, GridItem } from '@chakra-ui/react'
import MyMap from '../components/MyMap'
import MyOrders from '../components/MyOrders'
import MyApp from './_app'
import MyTabs from '../components/MyTabs'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="row">
        <Sidebar />
        <Box p={6}>
          <MyMap />
          <br />
          <MyTabs />
          <br />
          <Grid templateColumns='repeat(3, 1fr)' gap={6}>
            <GridItem><MyOrders order="324124" name="Barcelona" worth="$1000.00" status="Delivered"/></GridItem>
            <GridItem><MyOrders order="415133" name="Real Madrid" worth="$150.00" status="Returned"/></GridItem>
            <GridItem><MyOrders order="416846" name="Lionel Messi" worth="$2500.00" status="Shipped"/></GridItem>
            <GridItem><MyOrders order="213456" name="Ronaldo" worth="$120.00" status="In-Progress"/></GridItem>
            <GridItem><MyOrders order="981521" name="Rolnaldinho" worth="$10.00" status="Shipped"/></GridItem>
          </Grid>
        </Box>
      </Flex>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
